'use client';

import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'next/navigation';
import { CheckCircle2, FileUp, LockKeyhole } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { SearchableDropdown } from '@/components/ui/SearchableDropdown';
import api from '@/lib/axios';

const input = 'mt-1 w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm focus:border-[#0e4778] focus:outline-none focus:ring-2 focus:ring-blue-100';
const base = { firstName: '', lastName: '', email: '', phone: '', jobRole: '', source: '', manpowerRequestId: '', resumeUrl: '' };

export default function CandidateCreateForm() {
  const router = useRouter(); const qc = useQueryClient(); const [form, setForm] = useState(base); const [fileName, setFileName] = useState(''); const [uploading, setUploading] = useState(false);
  const { data: requests = [] } = useQuery<any[]>({ queryKey: ['manpower-request'], queryFn: async () => (await api.get('/hiring/manpower-request')).data });
  const approved = requests.filter((request) => request.status === 'Approved');
  const create = useMutation({ mutationFn: async () => (await api.post('/hiring/candidates', form)).data, onSuccess: () => { qc.invalidateQueries({ queryKey: ['candidates'] }); router.push('/dashboard/hiring/pipeline'); } });
  const upload = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setUploading(true); try { const data = new FormData(); data.append('file', file); const result = await api.post('/upload', data, { headers: { 'Content-Type': 'multipart/form-data' } }); setForm({ ...form, resumeUrl: result.data.url }); setFileName(file.name); } finally { setUploading(false); } };
  return <div className="mx-auto max-w-6xl pb-2 w-full px-2 md:px-0"><div className="border-b-2 border-[#0e4778] pb-3"><p className="text-xs font-md uppercase tracking-wider text-[#0e4778]">Hiring sequence · Step 2</p><h1 className="mt-1 text-2xl font-extrabold text-slate-950">Candidate Intake Form</h1><p className="mt-1 text-sm text-slate-600">A candidate can only be added against an approved Manpower Requisition. The requisition details remain linked and visible throughout the workflow.</p></div><Card className="mt-4 border-slate-200 w-full"><CardContent className="p-4"><form className="grid gap-3 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); create.mutate(); }}><label className="md:col-span-2"><span className="text-xs font-md uppercase">Approved Manpower Requisition *</span><div className="mt-1"><SearchableDropdown options={approved.map((request: any) => ({ label: `${request.jobTitle} · ${request.designation || '—'} · ${request.locationBranchId?.name || 'Location'}`, value: request._id }))} value={form.manpowerRequestId} onChange={(val) => setForm({ ...form, manpowerRequestId: val })} placeholder="Select approved request" /></div>{!approved.length && <p className="mt-2 flex items-center gap-1 text-xs text-amber-700"><LockKeyhole size={13} /> First create and approve a Manpower Requisition.</p>}</label>{[['firstName', 'First Name'], ['lastName', 'Last Name'], ['email', 'Email'], ['phone', 'Phone'], ['jobRole', 'Job Role']].map(([name, title]) => <label key={name}><span className="text-xs font-md uppercase">{title} *</span><input required type={name === 'email' ? 'email' : 'text'} className={input} value={(form as any)[name]} onChange={(event) => setForm({ ...form, [name]: event.target.value })} /></label>)}<label><span className="text-xs font-md uppercase">Source</span><select className={input} value={form.source} onChange={(event) => setForm({ ...form, source: event.target.value })}><option value="">Select source</option><option>LinkedIn</option><option>Referral</option><option>Website</option><option>Agency</option></select></label><label className="md:col-span-2"><span className="text-xs font-md uppercase">Resume (PDF/DOCX)</span><span className="mt-1 flex cursor-pointer items-center gap-2 rounded-md border border-dashed border-slate-300 px-3 py-3 text-sm"><>{form.resumeUrl ? <CheckCircle2 size={16} className="text-emerald-600" /> : <FileUp size={16} />}</><span>{uploading ? 'Uploading…' : fileName || 'Attach resume for the AI screening queue'}</span><input className="hidden" type="file" accept=".pdf,.docx" onChange={upload} /></span></label><Button className="md:col-span-2 bg-[#0e4778] hover:bg-[#073a69]" disabled={create.isPending || uploading || !approved.length}>{create.isPending ? 'ADDING…' : 'ADD CANDIDATE'}</Button></form></CardContent></Card></div>;
}
