'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import api from '@/lib/axios';

const STAGES = ['Applied', 'Screening', 'Interviewing', 'Offered', 'Hired', 'Rejected'];

export default function CandidatePipeline() {
  const router = useRouter(); const queryClient = useQueryClient();
  const { data: candidates, isLoading } = useQuery<any[]>({ queryKey: ['candidates'], queryFn: async () => (await api.get('/hiring/candidates')).data });
  const updateStatus = useMutation({ mutationFn: async ({ id, status }: { id: string; status: string }) => (await api.put(`/hiring/candidates/${id}/status`, { status })).data, onSuccess: () => queryClient.invalidateQueries({ queryKey: ['candidates'] }) });
  return <div className="mx-auto flex max-w-[1600px] flex-col gap-4 pb-8"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-zinc-100 pb-3 dark:border-zinc-800"><div><p className="text-[11px] font-md uppercase tracking-wider text-indigo-600">Hiring process</p><h1 className="mt-1 text-xl font-md">Candidate Pipeline</h1><p className="mt-1 text-sm text-zinc-500">Track candidates by current hiring stage. Open a card for the full 24-step workflow.</p></div><Button className="bg-indigo-600 hover:bg-indigo-700" onClick={() => router.push('/dashboard/hiring/candidates/new')}>Add Candidate</Button></div><div className="flex gap-4 overflow-x-auto pb-4">{isLoading ? <p className="py-10 text-sm text-zinc-500">Loading pipeline…</p> : STAGES.map((stage) => { const rows = (candidates || []).filter((candidate) => candidate.status === stage); return <section key={stage} className="w-[290px] shrink-0 rounded-xl border border-zinc-200 bg-zinc-50/70 p-3 dark:border-zinc-800 dark:bg-zinc-900/50"><div className="mb-3 flex justify-between"><h2 className="text-xs font-md uppercase tracking-wide">{stage}</h2><span className="rounded-full bg-zinc-200 px-2 py-0.5 text-xs font-md dark:bg-zinc-800">{rows.length}</span></div><div className="space-y-2">{rows.map((candidate) => <article key={candidate._id} className="rounded-lg border border-zinc-200 bg-white p-3 shadow-sm dark:border-zinc-700 dark:bg-zinc-800"><button className="w-full text-left" onClick={() => router.push(`/dashboard/hiring/${candidate._id}`)}><p className="text-sm font-md">{candidate.firstName} {candidate.lastName}</p><p className="mt-0.5 text-xs font-medium text-indigo-600">{candidate.jobRole}</p><p className="mt-2 truncate text-[11px] text-zinc-500">{candidate.email}</p></button><div className="mt-3 flex gap-1 border-t border-zinc-100 pt-2 dark:border-zinc-700">{stage !== 'Applied' && <Button variant="outline" className="h-7 flex-1 px-1 text-[10px]" onClick={() => updateStatus.mutate({ id: candidate._id, status: STAGES[STAGES.indexOf(stage) - 1] })}>Back</Button>}{!['Hired', 'Rejected'].includes(stage) && <Button variant="outline" className="h-7 flex-1 px-1 text-[10px]" onClick={() => updateStatus.mutate({ id: candidate._id, status: STAGES[STAGES.indexOf(stage) + 1] })}>Move</Button>}{!['Hired', 'Rejected'].includes(stage) && <Button variant="ghost" className="h-7 px-1 text-[10px] text-rose-600" onClick={() => updateStatus.mutate({ id: candidate._id, status: 'Rejected' })}>Reject</Button>}</div></article>)}{!rows.length && <p className="py-6 text-center text-xs text-zinc-400">No candidates</p>}</div></section>; })}</div></div>;
}
